apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mail-{{ .Values.DOMAIN }}-tls
  namespace: {{ .Values.namespace }}
spec:
  secretName: mail-{{ .Values.DOMAIN }}-tls
  dnsNames:
    - mail.{{ .Values.DOMAIN }}
    - smtp.{{ .Values.DOMAIN }}
    - imap.{{ .Values.DOMAIN }}
  issuerRef:
    name: {{ .Values.ISSUER_NAME }}
    kind: ClusterIssuer
