# -----------------------------------------
# 1.1. PersistentVolume for mail-config
# -----------------------------------------
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mail-config-pv
  labels:
    {{- include "mail-storage.labels" . | nindent 4 }}
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-mail-config
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .Values.EMAIL_NODE }}
  hostPath:
    path: /tmp/docker-mailserver
    type: DirectoryOrCreate
---
# -----------------------------------------
# 2.1. PersistentVolume for mail-data
# -----------------------------------------
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mail-data-pv
  labels:
    {{- include "mail-storage.labels" . | nindent 4 }}
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-mail-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .Values.EMAIL_NODE }}
  hostPath:
    path: /var/mail
    type: DirectoryOrCreate
---
# -----------------------------------------
# 3.1. PersistentVolume for mail-state
# -----------------------------------------
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mail-state-pv
  labels:
    {{- include "mail-storage.labels" . | nindent 4 }}
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-mail-state
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .Values.EMAIL_NODE }}
  hostPath:
    path: /var/mail-state
    type: DirectoryOrCreate
---
# -----------------------------------------
# 4.1. PersistentVolume for mail-log
# -----------------------------------------
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mail-log-pv
  labels:
    {{- include "mail-storage.labels" . | nindent 4 }}
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-mail-log
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .Values.EMAIL_NODE }}
  hostPath:
    path: /var/log/mail
    type: DirectoryOrCreate
---
# StorageClasses
# ---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-mail-config
  labels:
    {{- include "mail-storage.labels" . | nindent 4 }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-mail-data
  labels:
    {{- include "mail-storage.labels" . | nindent 4 }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-mail-state
  labels:
    {{- include "mail-storage.labels" . | nindent 4 }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-mail-log
  labels:
    {{- include "mail-storage.labels" . | nindent 4 }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
