apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.DOMAIN }}-tls
  namespace: {{ .Release.Namespace }}
  annotations:
  labels:
    {{- include "ingress-cert.labels" . | nindent 4 }}
spec:
  secretName: {{ .Values.DOMAIN }}-tls
  dnsNames:
    - {{ .Values.DOMAIN }}
    - mail.{{ .Values.DOMAIN }}
    - smtp.{{ .Values.DOMAIN }}
    - imap.{{ .Values.DOMAIN }}
    - freetj.{{ .Values.DOMAIN }}
    - freev2.{{ .Values.DOMAIN }}
    - freexr.{{ .Values.DOMAIN }}
  issuerRef:
    name: {{ .Values.ISSUER_NAME }}
    kind: ClusterIssuer
