apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.clusterIssuer.name }}
  namespace: {{ .Values.certManagerNamespace }}
spec:
  acme:
    server: {{ .Values.ACME_SERVER }}
    email: {{ .Values.EMAIL }}
    privateKeySecretRef:
      name: {{ .Values.clusterIssuer.privateKeySecret }}
    solvers:
      - http01:
          ingress:
            class: {{ .Values.clusterIssuer.ingressClass }}
