{{- $isProd := eq .Values.Environment "prod" -}}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.ISSUER_NAME }}
  labels:
    {{- include "ingress-cert.labels" . | nindent 4 }}
spec:
  {{- if $isProd }}
  acme:
    server: "https://acme-v02.api.letsencrypt.org/directory"
    email: {{ .Values.EMAIL }}
    privateKeySecretRef:
      name: {{ .Values.ISSUER_NAME }}
    solvers:
      - http01:
          ingress:
            class: "traefik"
  {{- else }}
  selfSigned: {}
  {{- end }}