apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dummy-page.fullname" . }}-html
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "dummy-page.fullname" . }}
data:
  index.html: |
{{ .Values.html.index | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dummy-page.fullname" . }}-nginx-conf
data:
  default.conf: |
    server {
        listen       80;
        server_name  _;
        root   /usr/share/nginx/html;
        index  index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }
    }