apiVersion: v1
kind: ConfigMap
metadata:
  name: trojan-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "free.labels" . | nindent 4 }}
data:
  config.json: |
    {
      "run_type": "server",
      "local_addr": "0.0.0.0",
      "local_port": 443,
      "remote_addr": "{{ .Values.DOMAIN }}",
      "remote_port": 80,
      "password": ["password2"],
      "log_level": 1,
      "ssl": {
        "verify": true,
        "verify_hostname": true,
        "cert": "/etc/tls/tls.crt",
        "key": "/etc/tls/tls.key",
        "key_password": "",
        "cipher": "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384",
        "cipher_tls13": "TLS_AES_128_GCM_SHA256:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384",
        "prefer_server_cipher": true,
        "alpn": ["http/1.1", "h2"],
        "reuse_session": true,
        "session_ticket": false,
        "session_timeout": 600,
        "plain_http_response": "",
        "curves": "",
        "dhparam": ""
      },
      "tcp": {
        "prefer_ipv4": false,
        "no_delay": true,
        "keep_alive": true,
        "reuse_port": false,
        "fast_open": false,
        "fast_open_qlen": 20
      },
      "mysql": {
        "enabled": false
      }
    }