apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: trojan-{{ include "free.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "free.labels" . | nindent 4 }}
spec:
  # Traefik entryPoint "mail-submissions" must be bound to port 465
  entryPoints:
    - websecure
  routes:
    - match: HostSNI(`freetj.{{ .Values.DOMAIN }}`)
      services:
        - name: trojan-{{ include "free.fullname" . }}
          port: {{ .Values.service.port }}
  tls:
    passthrough: true