name: "Init helmfile"
description: "Installs Helmfile, loads plugin cache, runs init with cache"
runs:
  using: "composite"
  steps:
      - uses: actions/cache@v3
        with:
          path: ~/.local/share/helm/plugins
          key: ${{ runner.os }}-helm-plugins-${{ hashFiles('**/helmfile.yaml') }}

      - uses: helmfile/helmfile-action@v2.0.4
        with:
          helmfile-version: 'v1.0.0'
          helm-version: 'v3.17.3'
          helm-plugins: >
            https://github.com/databus23/helm-diff,
            https://github.com/jkroepke/helm-secrets,
            https://github.com/hypnoglow/helm-s3.git,
            https://github.com/aslafy-z/helm-git
          helmfile-args: init

      - uses: helmfile/helmfile-action@v2.0.4
        with:
          helmfile-args: deps
