name: Helm CI: Lint, Install, and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set up KinD cluster
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: v0.20.0

      - name: Create KinD cluster
        run: kind create cluster --name helm-test

      - name: Find all Helm charts
        id: charts
        run: |
          # find every directory that has a Chart.yaml
          echo "::set-output name=dirs::$(find . -type f -name 'Chart.yaml' -exec dirname {} \; | tr '\n' ' ')"

      - name: Lint, template, install & test
        run: |
          for chart in ${{ steps.charts.outputs.dirs }}; do
            echo "→ Processing chart: $chart"

            # update dependencies (if any)
            helm dependency update "$chart"

            # lint
            helm lint "$chart"

            # render manifests client‑side
            helm template "$chart" | kubectl apply --dry-run=client -f -

            # install into Kind
            release="ci-$(basename $chart)"
            helm install "$release" "$chart" --wait --timeout 2m

            # run any defined tests (e.g. templates/tests/test-connection.yaml)
            helm test "$release" --timeout 1m || true

            # clean up release
            helm uninstall "$release"
          done

      - name: Delete KinD cluster
        run: kind delete cluster --name helm-test
