# TLS certificate replicated from cert-manager namespace.
# Ref: https://github.com/mittwald/kubernetes-replicator
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.DOMAIN }}-tls
  namespace: {{ .Release.Namespace }}
  annotations:
    replicator.v1.mittwald.de/replicate-from: cert-manager/{{ .Values.DOMAIN }}-tls
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: kubernetes.io/tls
data:
  tls.key: ""
  tls.crt: ""
  ca.crt: ""
