name: CD Helmfile

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    # require manual approval in GitHub → Settings → Environments → production
    environment: prod
    steps:
      # - name: Manual approval
      #   uses: trstringer/manual-approval@v1
      #   with:
      #     secret: ${{ github.TOKEN }}
      #     approvers: ${{ github.actor }} # myself
      #     minimum-approvals: 1
      #     exclude-workflow-initiator-as-approver: false
      #     fail-on-denial: true
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: helmfile-manifests
          path: ./
      - run: |
          cd ./helmfile-manifests
          # artifacts come from the triggering workflow_run
          # run-id: ${{ github.event.workflow_run.id }}
      
      - uses: ./.github/actions/helmfile-init

      - name: Configure KUBECONFIG
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.VPS_KUBECONFIG }}" | base64 -d > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
        env:
          KUBECONFIG: $HOME/.kube/config
      
      - name: Dry‑run (Diff) before Apply
        uses: helmfile/helmfile-action@v2.0.4
        with:
          helmfile-args: diff --environment prod --detailed-exitcode
        
        # This acts as a dry‑run check :contentReference[oaicite:9]{index=9}

      - name: Apply Changes
        uses: helmfile/helmfile-action@v2.0.4
        with:
          helmfile-args: apply --environment prod
        # performs actual sync if diff detected :contentReference[oaicite:10]{index=10}