name: CD Helmfile

on:
  workflow_dispatch:
  workflow_run:
    workflows: [CI Helmfile]
    types:
      - completed
    branches:
      - main

jobs:
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed, deployment skipped.' && exit 1
  deploy:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'workflow_dispatch' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    # require manual approval in GitHub → Settings → Environments → production
    environment: prod
    steps:
      # - name: Manual approval
      #   uses: trstringer/manual-approval@v1
      #   with:
      #     secret: ${{ github.TOKEN }}
      #     approvers: ${{ github.actor }} # myself
      #     minimum-approvals: 1
      #     exclude-workflow-initiator-as-approver: false
      #     fail-on-denial: true
      - uses: actions/checkout@v4
      
      - uses: ./.github/actions/helmfile-init

      - name: Configure KUBECONFIG
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.VPS_KUBECONFIG }}" | base64 -d > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
        env:
          KUBECONFIG: $HOME/.kube/config

      - name: Write secrets monitoring
        run: echo "${{ secrets.SECRETS_MONITORING }}" > ./secrets/monitoring.env

      - name: Apply secrets
        run: |
          ./scripts/apply-secrets.sh
      
      - name: Dry‑run (Diff) before Apply
        uses: helmfile/helmfile-action@v2.0.4
        with:
          helmfile-args: diff --environment prod --detailed-exitcode
        continue-on-error: true
        # This acts as a dry‑run check :contentReference[oaicite:9]{index=9}

      - name: Apply Changes
        uses: helmfile/helmfile-action@v2.0.4
        with:
          helmfile-args: apply --environment prod
        # performs actual sync if diff detected :contentReference[oaicite:10]{index=10}