name: CI Helmfile

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-dry-run:
    name: Lint, Diff, Render, Dry‑Run, Upload
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Helm plugins
        uses: actions/cache@v3
        with:
          path: ~/.local/share/helm/plugins
          key: ${{ runner.os }}-helm-plugins-${{ hashFiles('**/helmfile.yaml') }}

      - name: Setup Helm & Helmfile + Plugins
        uses: helmfile/helmfile-action@v2.0.4
        with:
          helmfile-version: 'v1.0.0'
          helm-version: 'v3.17.3'
          helm-plugins: >
            https://github.com/databus23/helm-diff,
            https://github.com/jkroepke/helm-secrets,
            https://github.com/hypnoglow/helm-s3.git,
            https://github.com/aslafy-z/helm-git
          helmfile-args: init

      - name: Lint all charts
        run: |
          helmfile lint

      - name: Show planned changes (diff)
        run: |
          helmfile -e prod diff
        continue-on-error: true

      - name: Render full manifests
        run: |
          mkdir -p rendered
          helmfile template --skip-deps -e prod --output-dir rendered

      - name: Dry‑run apply rendered YAML
        # client‑side dry‑run doesn’t require a live cluster
        run: |
          kubectl apply --validate=false --dry-run=client --recursive -f rendered/

      # Disabled for now since cd uses helmfile directly.
      #
      # - name: Upload rendered manifests only on main
      #   if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: helmfile-manifests
      #     path: ./
      #     if-no-files-found: error
