name: CI Helmfile

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: ./.github/actions/helmfile-init

      - uses: helmfile/helmfile-action@v2.0.4
        with:
          helmfile-args: deps

      - uses: helmfile/helmfile-action@v2.0.4
        with:
          helmfile-args: lint

      - run: |
          mkdir -p rendered
          helmfile template --skip-deps -e prod --output-dir rendered
          
      - uses: actions/upload-artifact@v4
        with:
          name: helmfile-manifests
          path: ./
